# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror -I/opt/homebrew/opt/readline/include

# Directories
SRCDIR = executing
BUILDDIR = build
TARGET = $(BUILDDIR)/minishell

# Source files
SRCS = $(wildcard $(SRCDIR)/*.c)
OBJS = $(SRCS:$(SRCDIR)/%.c=$(BUILDDIR)/%.o)

# Default target
all: $(TARGET)

# Build target
$(TARGET): $(OBJS)
    $(CC) $(CFLAGS) -o $@ $^

# Compile source files to object files
$(BUILDDIR)/%.o: $(SRCDIR)/%.c | $(BUILDDIR)
    $(CC) $(CFLAGS) -c $< -o $@

# Create build directory if it doesn't exist
$(BUILDDIR):
    mkdir -p $(BUILDDIR)

# Clean build files
clean:
    rm -f $(OBJS)

fclean: clean
    rm -f $(TARGET)

re: fclean all

.PHONY: all clean fclean re